package(default_visibility = ["//visibility:public"])

py_library(
    name = "optimizers",
    srcs = [
        "__init__.py",
    ],
    data = [
        "//tfmiss/keras/optimizers/schedules",
    ],
    srcs_version = "PY2AND3",
)
