package(default_visibility = ["//visibility:public"])

# py_library(
#     name = "metrics",
#     srcs = [
#         "__init__.py",
#         "f1.py",
#     ],
#     srcs_version = "PY2AND3",
# )

# py_test(
#     name = "f1_test",
#     srcs = ["f1_test.py"],
#     srcs_version = "PY2AND3",
#     deps = [":metrics"],
# )
