py_binary(
    name = "adaprive_softmax/best_splits/test_device",
    srcs = [
        "adaprive_softmax/best_splits/test_device.py",
    ],
    deps = [
        "//tfmiss",
    ],
)

py_binary(
    name = "adaprive_softmax/best_splits/best_splits",
    srcs = [
        "adaprive_softmax/best_splits/best_splits.py",
    ],
    deps = [
        "//tfmiss",
    ],
)

py_binary(
    name = "adaprive_softmax/text8/text8_test",
    srcs = [
        "adaprive_softmax/text8/text8_test.py",
        "adaprive_softmax/text8/model.py",
        "adaprive_softmax/text8/utils.py",
    ],
    deps = [
        "//tfmiss",
    ],
)

py_binary(
    name = "qrnn/imdb/imdb_test",
    srcs = [
        "qrnn/imdb/imdb_test.py",
        "qrnn/imdb/model.py",
        "qrnn/imdb/utils.py",
    ],
    deps = [
        "//tfmiss",
    ],
)
