py_binary(
    name = "adaprive_softmax/best_splits/test_device",
    srcs = [
        "adaprive_softmax/best_splits/test_device.py",
    ],
    deps = [
        "//tfmiss",
    ],
)

py_binary(
    name = "adaprive_softmax/best_splits/best_splits",
    srcs = [
        "adaprive_softmax/best_splits/best_splits.py",
    ],
    deps = [
        "//tfmiss",
    ],
)

py_binary(
    name = "adaprive_softmax/text8/text8_test",
    srcs = [
        "adaprive_softmax/text8/text8_test.py",
        "adaprive_softmax/text8/model.py",
        "adaprive_softmax/text8/utils.py",
    ],
    deps = [
        "//tfmiss",
    ],
)

py_binary(
    name = "tcn/adding_problem/add_test",
    srcs = [
        "tcn/adding_problem/add_test.py",
        "tcn/adding_problem/model.py",
        "tcn/adding_problem/utils.py",
    ],
    deps = [
        "//tfmiss",
    ],
)

py_binary(
    name = "tcn/char_cnn/char_test",
    srcs = [
        "tcn/char_cnn/char_test.py",
        "tcn/char_cnn/model.py",
        "tcn/char_cnn/utils.py",
    ],
    deps = [
        "//tfmiss",
    ],
)


py_binary(
    name = "tcn/copy_memory/copy_test",
    srcs = [
        "tcn/copy_memory/copy_test.py",
        "tcn/copy_memory/model.py",
        "tcn/copy_memory/utils.py",
    ],
    deps = [
        "//tfmiss",
    ],
)

py_binary(
    name = "tcn/mnist_pixel/mnist_test",
    srcs = [
        "tcn/mnist_pixel/mnist_test.py",
        "tcn/mnist_pixel/model.py",
        "tcn/mnist_pixel/utils.py",
    ],
    deps = [
        "//tfmiss",
    ],
)

py_binary(
    name = "weight_norm/cifar10/cifar10_test",
    srcs = [
        "weight_norm/cifar10/cifar10_test.py",
        "weight_norm/cifar10/model.py",
        "weight_norm/cifar10/utils.py",
    ],
    deps = [
        "//tfmiss",
    ],
)
