package(default_visibility = ["//visibility:public"])

py_library(
    name = "keras",
    srcs = [
        "__init__.py",
    ],
    data = [
        "//tfmiss/keras/callbacks",
        "//tfmiss/keras/layers",
         "//tfmiss/keras/losses",
         "//tfmiss/keras/metrics",
         "//tfmiss/keras/optimizers"
    ],
    srcs_version = "PY2AND3",
)
