package(default_visibility = ["//visibility:public"])

py_library(
    name = "keras",
    srcs = ([
        "__init__.py",
    ]),
    data = [
        ":layers",
#        ":optimizers",
    ],
    srcs_version = "PY2AND3",
)
