package(default_visibility = ["//visibility:public"])

py_library(
    name = "seq2seq",
    srcs = [
        "__init__.py",
    ],
    data = [
        ":transformer",
    ],
    srcs_version = "PY2AND3",
)
